POST http://localhost:3003/register
content-type: application/json

{
    "firstName": "Joanita",
    "lastName": "Nakityo",
    "email": "anita@gmail.com",
    "password": "1234"

}

###

GET http://localhost:3003/

###

GET http://localhost:3003/submitPreference

###
GET http://localhost:3003/submitPreference/61cb6a59d6a72f5dd3b6c541

###
GET http://localhost:3003/login
