POST http://localhost:3003/register
content-type: application/json

{
    "firstName": "Maria",
    "lastName": "Agatha",
    "email": "mariaagatha@gmail.com",
    "password": "123456"

}

###

GET http://localhost:3003/

###

GET http://localhost:3003/submitPreference

###
GET http://localhost:3003/submitPreference/6203de51308b7780452f6cd1

###
POST http://localhost:3003/login
Content-Type: application/json

{
    "email":"mariaagatha@gmail.com",
    "password":"123456"
}

###

POST http://localhost:3003/update/61cb6a59d6a72f5dd3b6c541
Content-Type: application/json

{
    "schoolName":"st.Francis"
}